[project]
name = "aoc2015"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "more-itertools>=10.7.0",
]

[tool.ruff]
target-version = "py313"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
