[project]
name = "aoc2015"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "deal>=4.24.5",
  "hypothesis>=6.131.25",
  "more-itertools>=10.7.0",
  "msgspec>=0.19.0",
  "trio>=0.30.0",
]

[dependency-groups]
dev = ["pytest>=8.3.5"]
